//
//	customUIButton.h
//	New Button
//
//	Created by jonbroFERrealz on 10/31/10
//	Copyright 2010 jonbroFERrealz
//	This code was generated by Opacity. You may use or modify it in any way.
//

#import <UIKit/UIKit.h>

extern const CGFloat kMyViewWidth;
extern const CGFloat kMyViewHeight;

@interface MyView : UIView
{
	CGFloat something;
}

@property (nonatomic) CGFloat something;

@end
