//
//	fileButtonView.h
//	New Image
//
//	Created by jonbroFERrealz on 10/13/10
//	Copyright 2010 jonbroFERrealz
//	This code was generated by Opacity. You may use or modify it in any way.
//

#import <UIKit/UIKit.h>

extern const CGFloat kMyViewWidth;
extern const CGFloat kMyViewHeight;

@interface MyView : UIView
{
	NSString *filename;
}

@property (copy, nonatomic) NSString *filename;

@end
